// @ts-nocheck
import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app'
};

const Home = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-4 bg-zinc-950 text-white">
      <h1 className="text-3xl font-bold">Welcome to Claude Code</h1>
      <Link href="/landing" className="mt-4 underline hover:text-indigo-600">Go to Landing Page</Link>
    </div>
  );
};

export default Home;